In [7]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers


In [8]:
# Define Sequential model with 3 layers
model = keras.Sequential(
    [
        layers.Dense(2, activation="relu", name="layer1"),
        layers.Dense(3, activation="relu", name="layer2"),
        layers.Dense(4, name="layer3"),
    ]
)
# Call model on a test input
x = tf.ones((3, 3))
y = model(x)

In [9]:
print(y)

tf.Tensor(
[[ 0.6101953  -0.15556318 -0.12077066 -0.19096269]
 [ 0.6101953  -0.15556318 -0.12077066 -0.19096269]
 [ 0.6101953  -0.15556318 -0.12077066 -0.19096269]], shape=(3, 4), dtype=float32)


In [10]:
print(x)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(3, 3), dtype=float32)


In [11]:
model.weights

[<KerasVariable shape=(3, 2), dtype=float32, path=sequential/layer1/kernel>,
 <KerasVariable shape=(2,), dtype=float32, path=sequential/layer1/bias>,
 <KerasVariable shape=(2, 3), dtype=float32, path=sequential/layer2/kernel>,
 <KerasVariable shape=(3,), dtype=float32, path=sequential/layer2/bias>,
 <KerasVariable shape=(3, 4), dtype=float32, path=sequential/layer3/kernel>,
 <KerasVariable shape=(4,), dtype=float32, path=sequential/layer3/bias>]

In [13]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ layer1 (Dense)                       │ (3, 2)                      │               8 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ layer2 (Dense)                       │ (3, 3)                      │               9 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ layer3 (Dense)                       │ (3, 4)                      │              16 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 33 (132.00 B)

 Trainable params: 33 (132.00 B)

 Non-trainable params: 0 (0.00 B)